### ISSUE TITLE
ImportError: cannot import name 'flash_attn_unpadded_qkvpacked_func' from 'flash_attn.flash_attn_interface'

### ISSUE THREAD

**Issue by CChBen** [HuangLK/transpeeder#38]
你好，我在执行`python convert2ckpt.py --mp_world_size 4 --model_name_or_path /path/to/llama-7b-hf --output_dir /path/to/llama-7b-init-ckpt`时报了以下错误：

`ImportError: cannot import name 'flash_attn_unpadded_qkvpacked_func' from 'flash_attn.flash_attn_interface'

看了下`flash_attn.flash_attn_interface`脚本里面确实没有`flash_attn_unpadded_qkvpacked_func`函数，我用的环境是pytorch1.13, python3.10, flash-attn.2.0.8, 能否提供下你的环境或者解决方案吗？

**Comment by HuangLK** [comment]
不好意思，这个代码库之前用的是flash-attn 1.x版本，还没有升级到flash-attn 2，你可以降级到[1.0.9](https://github.com/Dao-AILab/flash-attention/releases/tag/v1.0.9)

**Comment by CChBen** [comment]
> 

我看这个网站里[https://mygit.osfipin.com/repository/494232964](url)写了2.x版本将`flash_attn_unpadded_qkvpacked_func` 更名成了 `flash_attn_varlen_qkvpacked_func`.

我在代码了使用了最新的命名，可以跑通生成相应的文件，就是还不知道后面的finetune会不会有问题。

**Comment by HuangLK** [comment]
你可以对比开启与关闭flash-attn的loss曲线，一般来说loss曲线的趋势是一致的，loss值也应该非常接近
